[project]
name = "redaction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pii-codex>=0.4.6",
    "presidio-analyzer>=2.2.360",
    "presidio-anonymizer>=2.2.360",
    "scrubadub>=2.0.1",
]
