[project]
name = "redaction"
version = "0.1.0"
description = "Simple redaction script"
readme = "README.md"
requires-python = "==3.10"
dependencies = [
    "presidio_analyzer==2.2.360",
    "presidio_anonymizer==2.2.360",
]
